routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::group(['middleware'=> 'auth'],function(){
    Route::get('/inicio',[App\Http\Controllers\HomeController::class,'index'])->middleware('verified');

    Route::get('/mi_perfil',[App\Http\Controllers\PerfilController::class,'inicio'])->middleware('verified');

    Route::get('/editar_perfil', [App\Http\Controllers\PerfilController::class, 'editarPerfil'])->name('perfil')->middleware('verified');
    Route::post('/actualizar_perfil',[App\Http\Controllers\PerfilController::class, 'actualizacionDatos'])->name('actualizarPerfil')->middleware('verified');

    Route::resource("/entradas", App\Http\Controllers\EntradaController::class)->parameters(["niveles"=>"nivel"])->middleware('verified');
    Route::get('/delete_entrada/{id}',[App\Http\Controllers\EntradaController::class,'deleteEntrada'])->name('delete.entrada')->middleware('verified');
    Route::get('/forcedelete_entrada/{id}',[App\Http\Controllers\EntradaController::class,'forceDelete'])->name('forcedelete.entrada')->middleware('verified');
    Route::get('/papelera_entradas',[App\Http\Controllers\EntradaController::class, 'papeleraEntradas'])->name('papelera.entradas')->middleware('verified');
    Route::get('/restaurar_entrada/{id}',[App\Http\Controllers\EntradaController::class, 'restaurarEntrada'])->name('restaurar.entrada')->middleware('verified');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('verified');

app/Models/Entrada.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Entrada extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    public function imagenes(){
        return $this->morphMany('App\Models\Imagen', 'modelo');
    }
}

app/Http/Controllers/EntradaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Entrada;
use App\Models\Imagen;

class EntradaController extends Controller
{
    public function index(){
        $entradas = Entrada::where('user_id','=',auth()->id())->get();
        return view('websystem.entrada.index',compact('entradas'));
    }

    public function create(){
        return view('websystem.entrada.create');
    }

    public function edit($id){
        $entrada = Entrada::where('slug','=',$id)->get()->first();
        return view('websystem.entrada.edit',compact('entrada'));
    }

    public function show($id){
        $entrada = Entrada::where('slug','=',$id)->get()->first();
        return view('websystem.entrada.show',compact('entrada'));
    }

    public function store(Request $request){
        $this->validate(
            $request, 
            //validation
            ['titulo' => 'required','cuerpo' => 'required'],
            //custom messages
            ['titulo.required' => 'El titulo es requerido', 'cuerpo.required' => 'El cuerpo o contenido es requerido']
        );
        $entrada = new Entrada;
        $entrada->titulo = $request->titulo;
        $entrada->cuerpo = $request->cuerpo;
        $entrada->slug = $request->titulo;
        $entrada->user_id = auth()->id();
        $entrada->save();

        if($request->imagen != null){
            $file = $request->file('imagen');
            //obtenemos el nombre del archivo
            $nombre =  time()."_".$file->getClientOriginalName();
            //indicamos que queremos guardar un nuevo archivo en el disco local
            \Storage::disk('public')->put($nombre,  \File::get($file));
    
            $imagen = new Imagen;
            $imagen->ruta = $nombre;
            $entrada->imagenes()->save($imagen);
        }

        return redirect('/entradas')->with('success', 'Entrada creada');
    }

    public function update(Request $request, $id){
        $this->validate(
            $request, 
            //validation
            ['titulo' => 'required','cuerpo' => 'required'],
            //custom messages
            ['titulo.required' => 'El titulo es requerido', 'cuerpo.required' => 'El cuerpo o contenido es requerido']
        );
        $entrada = Entrada::find($id);
        $entrada->titulo = $request->titulo;
        $entrada->cuerpo = $request->cuerpo;
        $entrada->slug = $request->titulo;
        $entrada->save();

        if($request->imagen != null){
            $file = $request->file('imagen');
            //obtenemos el nombre del archivo
            $nombre =  time()."_".$file->getClientOriginalName();
            //indicamos que queremos guardar un nuevo archivo en el disco local
            \Storage::disk('public')->put($nombre,  \File::get($file));
    
            $imagen = new Imagen;
            $imagen->ruta = $nombre;
            $entrada->imagenes()->save($imagen);
        }
       
        return redirect('/entradas')->with('success', 'Entrada actualizada');
    }

    public function deleteEntrada($id){
        Entrada::find($id)->delete();
        return redirect('/entradas')->with('success', 'Entrada reciclada (ve a la papelera si deseas restaurar)');
    }

    public function forceDelete($id){
       $entrada =  Entrada::onlyTrashed()->find($id);

       foreach($entrada->imagenes as $item){
        unlink(storage_path('app/public/'.$item->ruta));
       }

        $entrada->forceDelete();

        return redirect('/papelera_entradas')->with('success', 'Entrada eliminada permanentemente');
    }

    public function papeleraEntradas(){
        $entradas = Entrada::where('user_id','=',auth()->id())->onlyTrashed()->get();
        return view('websystem.entrada.delete',compact('entradas'));
    }

    public function restaurarEntrada($id){
        Entrada::onlyTrashed()->find($id)->restore();
        return redirect('/papelera_entradas')->with('success', 'Entrada restaurada');
    }
}

resources/views/websystem/entrada/create.blade.php
@extends('template.app')
@section('content')
<div>
<form method="POST" action="{{route('entradas.store')}}" enctype="multipart/form-data">
    @csrf
    <div class="card mb-3" style="display: table; margin: 0 auto;">
        <div class="row no-gutters">
            <div>
                <div class="card-body">
                    <div>
                        <label>Titulo:</label>
                        <input type="text" placeholder="Ingresa un titulo" name="titulo" class="form-control @error('titulo') is-invalid @enderror" value="">
                        @error('titulo')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <br><br>
                        <textarea class="ckeditor" name="cuerpo" rows="10" cols="80">
                        </textarea>

                        @error('cuerpo')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <label class="mt-3">Selecciona un archivo para tu entrada:</label>
                        <input type="file" class="form-control-file" name="imagen" accept="image/*" >
                        <div class="text-center">
                            <button class="mt-3 btn btn-primary" type="submit">Guardar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
@endsection

resources/views/websystem/entrada/delete.blade.php
@extends('template.app')
@section('content')
@if(session()->get('success'))
  <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{ session()->get('success') }}  
  </div> 
  <br />
@endif
    @if(count($entradas))
    <table class="table table-dark">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Contenido</th>
        <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach($entradas as $item)
            <tr>
                <th scope="row">{{$item->id}}</th>
                <td>{{$item->titulo}}</td>
                <td>{{$item->cuerpo}}</td>
                <td><a href="{{ route('restaurar.entrada',$item->id)}}" class="btn btn-danger">Restaurar</a>
                <a href="{{ route('forcedelete.entrada',$item->id)}}" class="btn btn-danger">Eliminar (permanente)</a>
                </td>
            </tr>
        @endforeach
    </tbody>
    </table>
    @else
    No tienes ninguna entrada reciclada
    @endif
@endsection

resources/views/websystem/entrada/edit.blade.php
@extends('template.app')
@section('content')
<div>
<form method="POST" action="{{route('entradas.update',$entrada->id)}}" enctype="multipart/form-data">
    @csrf
    <input name="_method" type="hidden" value="PATCH">

    <div class="card mb-3" style="display: table; margin: 0 auto;">
        <div class="row no-gutters">
            <div>
                <div class="card-body">
                    <div>
                        <label>Titulo:</label>
                        <input type="text" placeholder="Ingresa un titulo" name="titulo" class="form-control @error('titulo') is-invalid @enderror" value="{{$entrada->titulo}}">
                        @error('titulo')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <br><br>
                        <textarea class="ckeditor" name="cuerpo" rows="10" cols="80">
                        {{$entrada->cuerpo}}
                        </textarea>

                        @error('cuerpo')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <label class="mt-3">Selecciona un archivo para tu entrada:</label>
                        <input type="file" class="form-control-file" name="imagen" accept="image/*" >
                        <div class="text-center">
                            <button class="mt-3 btn btn-primary" type="submit">Guardar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
@endsection

resources/views/websystem/entrada/index.blade.php
@extends('template.app')
@section('content')
@if(session()->get('success'))
  <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{ session()->get('success') }}  
  </div> 
  <br />
@endif
@if(count($entradas))
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Contenido</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    @foreach($entradas as $item)
        <tr>
            <th scope="row">{{$item->id}}</th>
            <td>{{$item->titulo}}</td>
            <td>{{$item->cuerpo}}</td>
            <td><a href="{{route('entradas.show',$item->slug)}}" class="btn btn-primary"><i class="far fa-eye"></i></a> 
            <a href="{{route('entradas.edit',$item->slug)}}" class="btn btn-warning"><i class="far fa-edit"></i></a>
            <a href="{{ route('delete.entrada',$item->id)}}" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
            </td>
        </tr>
    @endforeach
  </tbody>
</table>
@else
No tienes ninguna entrada creada
@endif

@endsection

resources/views/websystem/entrada/show.blade.php
@extends('template.app')
@section('content')
<div class="card mb-3" style="display: table; margin: 0 auto;">
        <div class="row no-gutters">
            <div>
                <div class="card-body">
                    <div>
                        <label>Titulo:<span>{{$entrada->titulo}}</span></label>
                        <br><br>
                        <textarea rows="10" cols="80">
                        {{$entrada->cuerpo}}
                        </textarea>
                        <br><br>
                        @foreach($entrada->imagenes as $item)
                        <img src="{{ asset('storage/'.$item->ruta) }}" alt="" title="" width="150" height="200" />
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection